frappe.query_reports["ZRA Tax Invoice Analysis"] = {
    filters: [
        {
            fieldname: "company",
            label: "Company",
            fieldtype: "Link",
            options: "Company",
            default: frappe.defaults.get_user_default("Company"),
        },
        {
            fieldname: "time_span",
            label: "Time Span",
            fieldtype: "Select",
            options: [
                "Today",
                "Yesterday",
                "This Week",
                "Last Week",
                "This Month",
                "Last Month",
                "This Year",
                "Period",
            ],
            default: "Today",
            reqd: 1,
        },
        {
            fieldname: "from_date",
            label: "From Date",
            fieldtype: "Date",
            depends_on: "eval:doc.time_span == 'Period'",
            mandatory_depends_on: "eval:doc.time_span == 'Period'",
        },
        {
            fieldname: "to_date",
            label: "To Date",
            fieldtype: "Date",
            depends_on: "eval:doc.time_span == 'Period'",
            mandatory_depends_on: "eval:doc.time_span == 'Period'",
        },
        {
            fieldname: "analysis_view",
            label: "Analysis View",
            fieldtype: "Select",
            options: [
                "Detail",
                "Daily Summary",
                "Tax Type Summary",
                "Status Summary",
                "Company Summary",
                "Document Type Summary",
            ],
            default: "Detail",
            reqd: 1,
        },
        {
            fieldname: "customer",
            label: "Customer",
            fieldtype: "Link",
            options: "Customer",
        },
        {
            fieldname: "sales_invoice",
            label: "Sales Invoice",
            fieldtype: "Link",
            options: "Sales Invoice",
        },
        {
            fieldname: "tax_type",
            label: "Tax Type",
            fieldtype: "Data",
        },
        {
            fieldname: "status",
            label: "Status",
            fieldtype: "Data",
        },
        {
            fieldname: "document_type",
            label: "ZRA Document Type",
            fieldtype: "Data",
        },
        {
            fieldname: "transaction_type",
            label: "Transaction Type",
            fieldtype: "Select",
            options: ["", "Normal", "Cancellation", "Correction"],
        },
        {
            fieldname: "receipt_number",
            label: "Receipt Number",
            fieldtype: "Data",
        },
        {
            fieldname: "znumber",
            label: "Z Number",
            fieldtype: "Data",
        },
    ],
};
